require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/eligible_admins", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EligibleAdmin. As you add validations to EligibleAdmin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EligibleAdmin.create! valid_attributes
      get eligible_admins_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      eligible_admin = EligibleAdmin.create! valid_attributes
      get eligible_admin_url(eligible_admin)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_eligible_admin_url
      expect(response).to(have_http_status(302))
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      eligible_admin = EligibleAdmin.create! valid_attributes
      get edit_eligible_admin_url(eligible_admin)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EligibleAdmin" do
        expect {
          post eligible_admins_url, params: { eligible_admin: valid_attributes }
        }.to change(EligibleAdmin, :count).by(1)
      end

      it "redirects to the created eligible_admin" do
        post eligible_admins_url, params: { eligible_admin: valid_attributes }
        expect(response).to redirect_to(eligible_admin_url(EligibleAdmin.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EligibleAdmin" do
        expect {
          post eligible_admins_url, params: { eligible_admin: invalid_attributes }
        }.to change(EligibleAdmin, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post eligible_admins_url, params: { eligible_admin: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested eligible_admin" do
        eligible_admin = EligibleAdmin.create! valid_attributes
        patch eligible_admin_url(eligible_admin), params: { eligible_admin: new_attributes }
        eligible_admin.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the eligible_admin" do
        eligible_admin = EligibleAdmin.create! valid_attributes
        patch eligible_admin_url(eligible_admin), params: { eligible_admin: new_attributes }
        eligible_admin.reload
        expect(response).to redirect_to(eligible_admin_url(eligible_admin))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        eligible_admin = EligibleAdmin.create! valid_attributes
        patch eligible_admin_url(eligible_admin), params: { eligible_admin: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested eligible_admin" do
      eligible_admin = EligibleAdmin.create! valid_attributes
      expect {
        delete eligible_admin_url(eligible_admin)
      }.to change(EligibleAdmin, :count).by(-1)
    end

    it "redirects to the eligible_admins list" do
      eligible_admin = EligibleAdmin.create! valid_attributes
      delete eligible_admin_url(eligible_admin)
      expect(response).to redirect_to(eligible_admins_url)
    end
  end
end
