require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/imagefiles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Imagefile. As you add validations to Imagefile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Imagefile.create! valid_attributes
      get imagefiles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      imagefile = Imagefile.create! valid_attributes
      get imagefile_url(imagefile)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_imagefile_url
      expect(response).to (have_http_status(302))
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      imagefile = Imagefile.create! valid_attributes
      get edit_imagefile_url(imagefile)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Imagefile" do
        expect {
          post imagefiles_url, params: { imagefile: valid_attributes }
        }.to change(Imagefile, :count).by(1)
      end

      it "redirects to the created imagefile" do
        post imagefiles_url, params: { imagefile: valid_attributes }
        expect(response).to redirect_to(imagefile_url(Imagefile.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Imagefile" do
        expect {
          post imagefiles_url, params: { imagefile: invalid_attributes }
        }.to change(Imagefile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post imagefiles_url, params: { imagefile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested imagefile" do
        imagefile = Imagefile.create! valid_attributes
        patch imagefile_url(imagefile), params: { imagefile: new_attributes }
        imagefile.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the imagefile" do
        imagefile = Imagefile.create! valid_attributes
        patch imagefile_url(imagefile), params: { imagefile: new_attributes }
        imagefile.reload
        expect(response).to redirect_to(imagefile_url(imagefile))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        imagefile = Imagefile.create! valid_attributes
        patch imagefile_url(imagefile), params: { imagefile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested imagefile" do
      imagefile = Imagefile.create! valid_attributes
      expect {
        delete imagefile_url(imagefile)
      }.to change(Imagefile, :count).by(-1)
    end

    it "redirects to the imagefiles list" do
      imagefile = Imagefile.create! valid_attributes
      delete imagefile_url(imagefile)
      expect(response).to redirect_to(imagefiles_url)
    end
  end
end
